### ISSUE TITLE
Are these fixes published on npm?

### ISSUE THREAD

**Issue by pognibene** [jhonber/react-native-bluetooth-serial#1]
Hello,
You've done some interesting fixes to this library (I've actually done more or less the same).
Are your changes published on npm? (ie if I do npm i reac-native-bluetooth-serial, is this your package version I will download, or the original (broken) one?

Thank you for your help!

Pascal

**Comment by jhonber** [comment]
Hello, the changes (Fixes) are not available on NPM.
But you can use NPM to install my fork (or any other on github):
```javascript
npm install --save jhonber/react-native-bluetooth-serial
```

the previous command adds the following entry in your package.json
```json
"dependencies": {
  "react-native-bluetooth-serial": "github:jhonber/react-native-bluetooth-serial"
}
```
